[package]
name = "induction"
version = "0.0.0"
authors = ["SpiveeWorks <spiveehere@gmail.com>"]

[dependencies]
piston_window = "0.74"
piston_app = { git = "https://github.com/spiveeworks/piston_app" }
