[package]
name = "city_internal"
version = "0.3.1"
authors = ["SpiveeWorks <spiveehere@gmail.com>"]

[dependencies]
lib-math = { path = "../lib-math" }
rand = "0.3"
sulphate-lib = { git = "https://github.com/spiveeworks/sulphate" }
